# Generated by Django 4.0.3 on 2023-02-17 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_num', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('copies', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200, null=True)),
                ('rollNo', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('academicYear', models.CharField(choices=[('I year', 'I year'), ('II year', 'II year'), ('III year', 'III year'), ('IV year', 'IV year')], max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowedOn', models.DateField(auto_now_add=True)),
                ('dueDate', models.DateField(null=True)),
                ('fineAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='panel.book')),
                ('borrrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.student')),
            ],
        ),
    ]
