# Generated by Django 4.0.3 on 2023-02-18 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='borrrower',
            new_name='borrower',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False, unique=True)),
                ('payment_timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='panel.book')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='panel.student')),
            ],
        ),
    ]
